version: 0.0.{build}
image: Visual Studio 2017
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
deploy:
  provider: NuGet
  api_key:
    secure: pczvLEg4nBMWMiSYU3fTN2sev61EqNsg0aLH0DcEDXZd3g0VzH5eVn25fqNWus3M
  ski_symbols: false
  artifact: /.*\.nupkg/
  